---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@a76c7b0547b8e4c16fdbbdb9d2ba3cbab144b168 # 20261002.1
    with:
      severity: warning
