---
name: Lint

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  actionlint:
    uses: timmo001/workflows/.github/workflows/lint-actionlint.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master

  markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master

  yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master

  jsonlint:
    uses: timmo001/workflows/.github/workflows/lint-jsonlint.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master

  markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master

  shellcheck:
    uses: timmo001/workflows/.github/workflows/lint-shellcheck.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master
    with:
      severity: warning
