---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

permissions:
  pull-requests: write
  contents: write

jobs:
  renovate-automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@8eac938d57bbcff242ec16ffbb3bbcea0d45b065 # master
