---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

permissions:
  pull-requests: write
  contents: write

jobs:
  renovate-automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@42a414fa5213eba2a71f3df0d6e7d94561f90e00 # master
